version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    container_name: namenode
 
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
    container_name: datanode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    container_name: hive-server

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    expose:
      - "9083"
    container_name: hive-metastore

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:latest
    container_name: hive-metastore-postgresql

  #hive-metastore-mysql:
    #image: mysql:5.7
    #image: arm64v8/mysql:oracle
    #restart: always
    #environment:
    #  MYSQL_DATABASE: 'mysqldb'
    #  MYSQL_USER: 'hive'
    #  MYSQL_PASSWORD: 'hive'
    #  MYSQL_ROOT_PASSWORD: 'hive'
    #ports:
    #  - '3306:3306'
    #expose:
    #  - '3306'
    #container_name: hive-metastore-mysql

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"
    container_name: presto-coordinator

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      net_pet:
        ipv4_address: 172.27.1.15
 
  nifi: 
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 9999:9999
    environment:
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min 
      - NIFI_SENSITIVE_PROPS_KEY=iksefhisfuzufdsfs
    volumes:
      - ./drivers:/drivers   
    networks:
      net_pet:
        ipv4_address: 172.27.1.18   
volumes:
  namenode:
  datanode:
  nifi:
  
 

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
