from apache/nifi:latest

#ARG DRIVER_NAME=postgresql-42.3.4.jar
#RUN mkdir -p /opt/big_data/
#RUN mkdir -p /opt/big_data/conf
#RUN mkdir -p /opt/big_data/conf/drivers
#RUN wget https://jdbc.postgresql.org/download/$DRIVER_NAME
#RUN cp $DRIVER_NAME /var/big_data/conf/drivers/$DRIVER_NAME


